apiVersion: v1
kind: Service
metadata:
  name: hello-api
  namespace: default
  labels:
    app: hello-api
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30081
    name: http
  selector:
    app: hello-api
